workflows:
  debug:
    name: RIA DigiDoc (MOPP2)
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: RIA DigiDoc (MOPP)
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: ee.ria.digidoc
      vars:
        BUNDLE_ID: "ee.ria.digidoc"
        XCODE_SCHEME: "MoppApp"
        APP_STORE_APPLE_ID: ET847QJV9F
      xcode: latest
    scripts:
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Increment build number
        script: | 
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - marten.rebane@nortal.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration

        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        submit_to_testflight: true

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: false
