# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MOPP POC' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MOPP POC

#pod 'OpenSSL'
end
