//
// Autogenerated by Laurine - by Jiri Trecak ( http://jiritrecak.com, @jiritrecak )
// Do not change this file manually!
//


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Imports

#import "Localizations.h"


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Header

@implementation _Localizations

- (NSString *)TabSigned {
    return NSLocalizedStringFromTable(@"tab-signed", nil, nil);
}

- (NSString *)TabSimSettings {
    return NSLocalizedStringFromTable(@"tab-sim-settings", nil, nil);
}

- (NSString *)TabMyEid {
    return NSLocalizedStringFromTable(@"tab-my-eid", nil, nil);
}

- (NSString *)TabSigning {
    return NSLocalizedStringFromTable(@"tab-signing", nil, nil);
}

+ (_Localizations *)sharedInstance {

    static dispatch_once_t once;
    static _Localizations *instance;
    dispatch_once(&once, ^{
        instance = [[_Localizations alloc] init];
    });
    return instance;
}
@end

