//
//  LocalizationKeys.swift
//  MoppApp
/*
 * Copyright 2017 Riigi Infosüsteemide Amet
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */

import Foundation


enum LocKey : String
{
    typealias RawValue = String
    
    case menuHelp = "menu-help"
    case menuIntro = "menu-intro"
    case menuFilemanager = "menu-filemanager"
    case menuSettings = "menu-settings"
    case menuAbout = "menu-about"
    case TabContainers = "tab-containers"
    case TabMyEid = "tab-my-eid"
    case TabSimSettings = "tab-sim-settings"
    case TabSettings = "tab-settings"
    case TabCrypto = "tab-crypto"
    case TabSignature = "tab-signature"
    case SignatureViewBeginLabel = "signature-view-begin-label"
    case SignatureViewBeginButton = "signature-view-begin-button"
    case CryptoViewBeginLabel = "crypto-view-begin-label"
    case CryptoViewBeginButton = "crypto-view-begin-button"
    case MyeidViewBeginLabel = "myeid-view-begin-label"
    case MyeidViewBeginButton = "myeid-view-begin-button"
    case MyeidViewBeginAltLabel = "myeid-view-begin-alt-label"
    case CrashlyticsTitle = "crashlytics-title"
    case CrashlyticsMessage = "crashlytics-message"
    case CrashlyticsActionSend = "crashlytics-action-send"
    case CrashlyticsActionAlwaysSend = "crashlytics-action-always-send"
    case CrashlyticsActionDoNotSend = "crashlytics-action-do-not-send"
    case ActionOk = "action-ok"
    case ActionCancel = "action-cancel"
    case ActionDelete = "action-delete"
    case ActionEdit = "action-edit"
    case ActionYes = "action-yes"
    case ActionNo = "action-no"
    case ActionCreateNewDocument = "action-create-new-document"
    case ActionAddToDocument = "action-add-to-document"
    case NoContainersCellTitle = "no-containers-cell-title"
    case ContainersListSearchPlaceholder = "containers-list-search-placeholder"
    case ContainersListSectionHeaderUnsigned = "containers-list-section-header-unsigned"
    case ContainersListSectionHeaderSigned = "containers-list-section-header-signed"
    case ContainersListCachedFilesTitle = "containers-list-cached-files-title"
    case ContainersListCachedFilesMessage = "containers-list-cached-files-message"
    case ContainersListCachedFilesOption1 = "containers-list-cached-files-option1"
    case ContainersListCachedFilesOption2 = "containers-list-cached-files-option2"
    case FileImportTitle = "file-import-title"
    case FileImportCreateContainerButton = "file-import-create-container-button"
    case FileImportInfo = "file-import-info"
    case FileImportImportFailedAlertTitle = "file-import-import-failed-alert-title"
    case FileImportImportFailedAlertMessage = "file-import-import-failed-alert-message"
    case ContainerDetailsTitle = "container-details-title"
    case ContainerDetailsHeaderDetails = "container-details-header-details"
    case ContainerDetailsDatafileSectionHeader = "container-details-datafile-section-header"
    case ContainerDetailsDatafileDetails = "container-details-datafile-details"
    case ContainerDetailsSignatureSectionHeader = "container-details-signature-section-header"
    case ContainerDetailsSignaturePrefix = "container-details-signature-prefix"
    case ContainerDetailsSignatureValid = "container-details-signature-valid"
    case ContainerDetailsSignatureInvalid = "container-details-signature-invalid"
    case ContainerDetailsEnterPin = "container-details-enter-pin"
    case ContainerDetailsGeneralError = "container-details-general-error"
    case ContainerDetailsSigningSuccess = "container-details-signing-success"
    case ContainerDetailsSignatureAdded = "container-details-signature-added"
    case ContainerDetailsSignatureAlreadyExists = "container-details-signature-already-exists"
    case ContainerDetailsSigningMethodAlertTitle = "container-details-signing-method-alert-title"
    case ContainerDetailsSigningMethodAlertMessage = "container-details-signing-method-alert-message"
    case ContainerDetailsSigningMethodMobileId = "container-details-signing-method-mobile-id"
    case ContainerDetailsSigningMethodIdCard = "container-details-signing-method-id-card"
    case ContainerDetailsIdcodePhoneAlertTitle = "container-details-idcode-phone-alert-title"
    case ContainerDetailsIdcodePhoneAlertMessage = "container-details-idcode-phone-alert-message"
    case ContainerDetailsIdcodePhoneAlertIdcodePlacholder = "container-details-idcode-phone-alert-idcode-placholder"
    case ContainerDetailsIdcodePhoneAlertPhonenumberPlacholder = "container-details-idcode-phone-alert-phonenumber-placholder"
    case ContainerDetailsPhoneNumberErrorAlertTitle = "container-details-phone-number-error-alert-title"
    case ContainerDetailsPhoneNumberErrorAlertMessage = "container-details-phone-number-error-alert-message"
    case ContainerDetailsRenameContainer = "container-details-rename-container"
    case ContainerDetailsRename = "container-details-rename"
    case ContainerDetailsEnterNewName = "container-details-enter-new-name"
    case ContainerDetailsName = "container-details-name"
    case ContainerDetailsReaderNotFound = "container-details-reader-not-found"
    case ContainerDetailsCardNotFound = "container-details-card-not-found"
    case ContainerDetailsPinNotProvided = "container-details-pin-not-provided"
    case ContainerDetailsSignatureAlreadyExistsAlertTitle = "container-details-signature-already-exists-alert-title"
    case ContainerDetailsSignatureAlreadyExistsAlertMessage = "container-details-signature-already-exists-alert-message"
    case ContainerDetailsFileAlreadyExists = "container-details-file-already-exists"
    case ContainerDetailsAttention = "container-details-attention"
    case ContainerDetailsStoreMobileIdCredentialsAlertTitle = "container-details-store-mobile-id-credentials-alert-title"
    case ContainerDetailsStoreMobileIdCredentialsAlertMessage = "container-details-store-mobile-id-credentials-alert-message"
    case ContainerDetailsFileNameTooLong = "container-details-file-name-too-long"
    case ContainerDetailsNameChangeFailed = "container-details-name-change-failed"
    case ContainerDetailsInternetConnectionErrorTitle = "container-details-internet-connection-error-title"
    case ContainerDetailsInternetConnectionErrorMessage = "container-details-internet-connection-error-message"
    case ContainerDetailsAddSignature = "container-details-add-signature"
    case MyEidIdCardInfo = "my-eid-id-card-info"
    case MyEidWarningCardNotFound = "my-eid-warning-card-not-found"
    case MyEidWarningReaderNotFound = "my-eid-warning-reader-not-found"
    case MyEidTapHere = "my-eid-tap-here"
    case MyEidSupportedReader = "my-eid-supported-reader"
    case MyEidFindMoreInfo = "my-eid-find-more-info"
    case MyEidGivenNames = "my-eid-given-names"
    case MyEidSurname = "my-eid-surname"
    case MyEidPersonalCode = "my-eid-personal-code"
    case MyEidBirth = "my-eid-birth"
    case MyEidCitizenship = "my-eid-citizenship"
    case MyEidEmail = "my-eid-email"
    case MyEidCardInReader = "my-eid-card-in-reader"
    case MyEidValidUntil = "my-eid-valid-until"
    case MyEidUseCount = "my-eid-use-count"
    case MyEidValidity = "my-eid-validity"
    case MyEidValid = "my-eid-valid"
    case MyEidNotValid = "my-eid-not-valid"
    case MyEidPersonalData = "my-eid-personal-data"
    case MyEidTimesUsed = "my-eid-times-used"
    case MyEidUsedOnce = "my-eid-used-once"
    case MyEidEid = "my-eid-eid"
    case MyEidSignatureCertificate = "my-eid-signature-certificate"
    case MyEidAuthenticationCertificate = "my-eid-authentication-certificate"
    case MyEidMyEid = "my-eid-my-eid"
    case MyEidIdCardInfoLink = "my-eid-id-card-info-link"
    case MyEidPinBlocked = "my-eid-pin-blocked"
    case MyEidPinActionsView = "my-eid-pin-actions-view"
    case PinActionsPin1 = "pin-actions-pin1"
    case PinActionsPin2 = "pin-actions-pin2"
    case PinActionsPuk = "pin-actions-puk"
    case PinActionsChangePin = "pin-actions-change-pin"
    case PinActionsUnblockPin = "pin-actions-unblock-pin"
    case PinActionsChangingPin = "pin-actions-changing-pin"
    case PinActionsTitleUnblockingPin = "pin-actions-title-unblocking-pin"
    case PinActionsCurrentPin = "pin-actions-current-pin"
    case PinActionsNewPin = "pin-actions-new-pin"
    case PinActionsRepeatPin = "pin-actions-repeat-pin"
    case PinActionsRulesTitle = "pin-actions-rules-title"
    case PinActionsRuleDifferentFromPrevious = "pin-actions-rule-different-from-previous"
    case PinActionsRuleNumbersOnly = "pin-actions-rule-numbers-only"
    case PinActionsRulePinLength = "pin-actions-rule-pin-length"
    case PinActionsRuleForbiddenPins = "pin-actions-rule-forbidden-pins"
    case PinActionsInfo = "pin-actions-info"
    case PinActionsGeneralError = "pin-actions-general-error"
    case PinActionsSameAsCurrent = "pin-actions-same-as-current"
    case PinActionsInvalidFormat = "pin-actions-invalid-format"
    case PinActionsWrongPinRetry = "pin-actions-wrong-pin-retry"
    case PinActionsWrongPinBlocked = "pin-actions-wrong-pin-blocked"
    case PinActionsErrorTitle = "pin-actions-error-title"
    case PinActionsSuccessTitle = "pin-actions-success-title"
    case PinActionsSuccessPinChanged = "pin-actions-success-pin-changed"
    case PinActionsSuccessPinUnblocked = "pin-actions-success-pin-unblocked"
    case PinActionsVerificationTitle = "pin-actions-verification-title"
    case PinActionsVerificationOption = "pin-actions-verification-option"
    case PinActionsUnblockingPin = "pin-actions-unblocking-pin"
    case PinActionsRepeatedPinDoesntMatch = "pin-actions-repeated-pin-doesnt-match"
    case PinActionsPinBlocked = "pin-actions-pin-blocked"
    case PinActionsPukChangeWarning = "pin-actions-puk-change-warning"
    case SettingsNewContainerFormat = "settings-new-container-format"
    case SettingsApplicationVersion = "settings-application-version"
    case SettingsAbout = "settings-about"
    case SettingsIdCodeTitle = "settings-id-code-title"
    case SettingsPhoneNumberTitle = "settings-phone-number-title"
    case SettingsIdCodeAlertMessage = "settings-id-code-alert-message"
    case SettingsPhoneNumberAlertMessage = "settings-phone-number-alert-message"
    case SettingsMobileIdHeader = "settings-mobile-id-header"
    case AboutDevelopment = "about-development"
    case AboutDependencies = "about-dependencies"
    case ChallengeCodeLabel = "challenge-code-label"
    case MobileIdTimeoutMessage = "mobile-id-timeout-message"
    case ErrorAlertTitleGeneral = "error-alert-title-general"
    case ShareExtensionImportTitle = "share-extension-import-title"
    case ShareExtensionImportMessage = "share-extension-import-message"
}
