source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

# Ignore warnings from pods
inhibit_all_warnings!

workspace 'MoppApp.xcworkspace'
project 'MoppApp.xcodeproj'
project '../MoppLib/MoppLib.xcodeproj'
project '../CryptoLib/CryptoLib'

platform :ios, '12.0'

target 'MoppApp' do
  platform :ios, '12.0'
  project 'MoppApp.xcodeproj'
  pod 'Firebase/Crashlytics', '~> 8.7.0'
  pod 'Firebase/Analytics', '~> 8.7.0'
  pod 'SwiftyRSA', '~> 1.7.0'
  pod 'ZIPFoundation', '~> 0.9'
  pod 'ILPDFKit', '~> 2.0.1'
end

target 'MoppAppTestEnv' do
  platform :ios, '12.0'
  project 'MoppApp.xcodeproj'

  pod 'Firebase/Crashlytics', '~> 8.7.0'
  pod 'Firebase/Analytics', '~> 8.7.0'
  pod 'SwiftyRSA', '~> 1.7.0'
end

target 'MoppLib' do
  platform :ios, '12.0'
  project '../MoppLib/MoppLib.xcodeproj'
  #pod 'Firebase/Crashlytics', '~> 8.7.0'
  #pod 'Firebase/Analytics', '~> 8.7.0'
end

target 'MoppLibTestEnv' do
  platform :ios, '12.0'
  project '../MoppLib/MoppLib.xcodeproj'
  #pod 'Firebase/Crashlytics', '~> 8.7.0'
  #pod 'Firebase/Analytics', '~> 8.7.0'
end

target 'CryptoLib' do
    platform :ios, '12.0'
    project '../CryptoLib/CryptoLib.xcodeproj'
    #pod 'Firebase/Crashlytics', '~> 8.7.0'
    #pod 'Firebase/Analytics', '~> 8.7.0'
end

target 'MoppLibTests' do
  platform :ios, '12.0'
  project '../MoppLib/MoppLib.xcodeproj'
  pod 'OCMock', '~> 3.8.1'

end

target 'SkSigningLib' do
    platform :ios, '12.0'
    project '../SkSigningLib/SkSigningLib.xcodeproj'
    #pod 'Firebase/Crashlytics', '~> 8.7.0'
    #pod 'Firebase/Analytics', '~> 8.7.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if Gem::Version.new('12.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
