use_frameworks!

workspace 'MoppApp.xcworkspace'
project 'MoppApp.xcodeproj'
project '../MoppLib/MoppLib.xcodeproj'
project '../CryptoLib/CryptoLib'

platform :ios, '9.0'

target 'MoppApp' do
  platform :ios, '9.0'
  project 'MoppApp.xcodeproj'

  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'Fabric'
  pod 'Crashlytics'
end

target 'MoppLib' do
  platform :ios, '9.0'
  project '../MoppLib/MoppLib.xcodeproj'
  #pod 'MBProgressHUD', '~> 0.9.2'
  #pod 'Fabric'
  #pod 'Crashlytics'
end

target 'CryptoLib' do
    platform :ios, '9.0'
    project '../CryptoLib/CryptoLib.xcodeproj'
    #pod 'MBProgressHUD', '~> 0.9.2'
    #pod 'Fabric'
    #pod 'Crashlytics'
end

target 'MoppLibTests' do
  platform :ios, '9.0'
  project '../MoppLib/MoppLib.xcodeproj'
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'OCMock'
  
end
